version: '3.8'
services:
  gateway:
    container_name: gateway
    build:
      context: gateway
      dockerfile: Dockerfile
    image: api-workshop/gateway:latest
    ports:
      - 8080:8080
  admin:
    container_name: admin
    build:
      context: admin
      dockerfile: Dockerfile
    image: api-workshop/admin:latest
  spring-service:
    container_name: spring-service
    build:
      context: spring-service
      dockerfile: Dockerfile
    image: api-workshop/spring-service:latest
    environment:
      - JAVA_OPTS=-Xmx256m -Xms128m
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 256M
  fast-api-service:
    container_name: fast-api-service
    build:
      context: fast-api-service
      dockerfile: Dockerfile
    image: api-workshop/fast-api-service:latest
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 256M
  node-service:
    container_name: node-service
    build:
      context: node-service
      dockerfile: Dockerfile
    image: api-workshop/node-service:latest
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 256M
  core-service:
    container_name: core-service
    build:
      context: core-service
      dockerfile: Dockerfile
    image: api-workshop/core-service:latest
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 256M
