version: '3.8'
services:
  gateway:
    container_name: gateway
    build:
      context: gateway
      dockerfile: Dockerfile
    image: api-workshop/gateway:latest
    ports:
      - 8080:8080
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
  fast-api-service:
    container_name: fast-api-service
    build:
      context: fast-api-service
      dockerfile: Dockerfile
    image: api-workshop/fast-api-service:latest
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
